name: Release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
    - uses: actions/setup-node@v3
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
    - name: Authenticate GitHub Packages
      run: cp .npmrc.config .npmrc && sed -i 's/_AUTH_TOKEN_/${{ secrets.NODE_AUTH_TOKEN }}/' .npmrc
    - run: yarn
    - run: yarn build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
